# -*- mode: python -*-
Import("env")
Import("wiredtiger")
Import("get_option")

env = env.Clone()

using_ubsan = False
sanitizer_list = get_option('sanitize')
if sanitizer_list:
    using_ubsan = 'undefined' in sanitizer_list.split(',')

env.Library(
    target='storage_wiredtiger_customization_hooks',
    source= [
        'wiredtiger_customization_hooks.cpp',
        'wiredtiger_extensions.cpp',
    ],
    LIBDEPS= ['$BUILD_DIR/mongo/base',
              '$BUILD_DIR/mongo/db/service_context'],
    PROGDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/mongod',
        '$BUILD_DIR/mongo/mongos',
    ],
)

if wiredtiger:
    wtEnv = env.Clone()
    wtEnv.InjectThirdParty(libraries=['wiredtiger'])
    wtEnv.InjectThirdParty(libraries=['zlib'])
    wtEnv.InjectThirdParty(libraries=['valgrind'])

    # This is the smallest possible set of files that wraps WT
    wtEnv.Library(
        target='storage_wiredtiger_core',
        source= [
            "../../../../../../../spdk/lib/wiredtiger/env_spdk.cc",
            'oplog_stones_server_status_section.cpp',
            'wiredtiger_begin_transaction_block.cpp',
            'wiredtiger_cursor.cpp',
            'wiredtiger_global_options.cpp',
            'wiredtiger_index.cpp',
            'wiredtiger_kv_engine.cpp',
            'wiredtiger_oplog_manager.cpp',
            'wiredtiger_parameters.cpp',
            'wiredtiger_prepare_conflict.cpp',
            'wiredtiger_record_store.cpp',
            'wiredtiger_recovery_unit.cpp',
            'wiredtiger_session_cache.cpp',
            'wiredtiger_snapshot_manager.cpp',
            'wiredtiger_size_storer.cpp',
            'wiredtiger_util.cpp',
            'wiredtiger_parameters.idl',
            ],
        LIBDEPS= [
            '$BUILD_DIR/mongo/base',
            '$BUILD_DIR/mongo/db/bson/dotted_path_support',
            '$BUILD_DIR/mongo/db/catalog/collection',
            '$BUILD_DIR/mongo/db/catalog/collection_options',
            '$BUILD_DIR/mongo/db/concurrency/lock_manager',
            '$BUILD_DIR/mongo/db/concurrency/write_conflict_exception',
            '$BUILD_DIR/mongo/db/curop',
            '$BUILD_DIR/mongo/db/index/index_descriptor',
            '$BUILD_DIR/mongo/db/global_settings',
            '$BUILD_DIR/mongo/db/namespace_string',
            '$BUILD_DIR/mongo/db/prepare_conflict_tracker',
            '$BUILD_DIR/mongo/db/repl/repl_coordinator_interface',
            '$BUILD_DIR/mongo/db/repl/repl_settings',
            '$BUILD_DIR/mongo/db/server_options_core',
            '$BUILD_DIR/mongo/db/service_context',
            '$BUILD_DIR/mongo/db/storage/index_entry_comparison',
            '$BUILD_DIR/mongo/db/storage/key_string',
            '$BUILD_DIR/mongo/db/storage/kv/kv_prefix',
            '$BUILD_DIR/mongo/db/storage/oplog_hack',
            '$BUILD_DIR/mongo/db/storage/recovery_unit_base',
            '$BUILD_DIR/mongo/db/storage/storage_file_util',
            '$BUILD_DIR/mongo/db/storage/storage_options',
            '$BUILD_DIR/mongo/util/concurrency/ticketholder',
            '$BUILD_DIR/mongo/util/elapsed_tracker',
            '$BUILD_DIR/mongo/util/processinfo',
            '$BUILD_DIR/third_party/shim_snappy',
            '$BUILD_DIR/third_party/shim_wiredtiger',
            '$BUILD_DIR/third_party/shim_zlib',
            'storage_wiredtiger_customization_hooks',
            ],
        # LINKFLAGS= [
        #     '-Wl,--whole-archive,-Wl,--no-as-needed,spdk_bdev_malloc,spdk_bdev_null,spdk_bdev_nvme,spdk_bdev_passthru,spdk_bdev_lvol,spdk_bdev_raid,spdk_bdev_error,spdk_bdev_gpt,spdk_bdev_split,spdk_bdev_delay,spdk_bdev_zone_block,spdk_blobfs_bdev,spdk_blobfs,spdk_blob_bdev,spdk_lvol,spdk_blob,spdk_nvme,spdk_bdev_ftl,spdk_ftl,spdk_bdev_aio,spdk_bdev_virtio,spdk_virtio,spdk_accel_ioat,spdk_ioat,spdk_sock_posix,spdk_event_bdev,spdk_bdev,spdk_notify,spdk_event_accel,spdk_accel,spdk_event_vmd,spdk_vmd,spdk_event_sock,spdk_event,spdk_thread,spdk_trace,spdk_sock,spdk_rpc,spdk_jsonrpc,spdk_json,spdk_util,spdk_log,-Wl,--no-whole-archive',
        #     '/home/denghejian/dir/spdk/build/lib/libspdk_env_dpdk.a',
        #     '-Wl,--whole-archive,/home/denghejian/dir/spdk/dpdk/build/lib/librte_eal.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_mempool.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_ring.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_mbuf.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_pci.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_bus_pci.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_mempool_ring.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_power.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_telemetry.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_kvargs.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_vhost.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_net.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_cryptodev.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_hash.a,/home/denghejian/dir/spdk/dpdk/build/lib/librte_rcu.a,-Wl,--no-whole-archive',
        #     'numa,isal,rt,uuid,crypto,aio',
        #     ],
        # LIBS= [
        #     'spdk_bdev_malloc',
        #     'spdk_bdev_null',
        #     'spdk_bdev_nvme',
        #     'spdk_bdev_passthru',
        #     'spdk_bdev_lvol',
        #     'spdk_bdev_raid',
        #     'spdk_bdev_error',
        #     'spdk_bdev_gpt',
        #     'spdk_bdev_split',
        #     'spdk_bdev_delay',
        #     'spdk_bdev_zone_block',
        #     'spdk_blobfs_bdev',       
        #     'spdk_blobfs',
        #     'spdk_blob_bdev',
        #     'spdk_lvol',
        #     'spdk_blob',
        #     'spdk_nvme',
        #     'spdk_bdev_ftl',
        #     'spdk_ftl',
        #     'spdk_bdev_aio',
        #     'spdk_bdev_virtio',
        #     'spdk_virtio',
        #     'spdk_accel_ioat',
        #     'spdk_ioat',
        #     'spdk_sock_posix',
        #     'spdk_event_bdev',
        #     'spdk_bdev',
        #     'spdk_notify',
        #     'spdk_event_accel',
        #     'spdk_accel',
        #     'spdk_event_vmd',
        #     'spdk_vmd',
        #     'spdk_event_sock',
        #     'spdk_event',
        #     'spdk_thread',
        #     'spdk_trace',
        #     'spdk_sock',
        #     'spdk_rpc',
        #     'spdk_jsonrpc',
        #     'spdk_json',
        #     'spdk_util',
        #     'spdk_log',
        #     'spdk_env_dpdk',
        #     # 'rte_eal',
        #     # 'rte_mempool',
        #     # 'rte_ring',
        #     # 'rte_mbuf',
        #     # 'rte_pci',
        #     # 'rte_bus_pci',
        #     # 'rte_mempool_ring',
        #     # 'rte_power',
        #     # 'rte_telemetry',
        #     # 'rte_kvargs',
        #     # 'rte_vhost',
        #     # 'rte_net',
        #     # 'rte_cryptodev',
        #     # 'rte_hash',
        #     # 'rte_rcu',
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_eal.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_mempool.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_ring.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_mbuf.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_pci.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_bus_pci.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_mempool_ring.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_power.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_telemetry.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_kvargs.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_vhost.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_net.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_cryptodev.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_hash.a'),
        #     File('/home/denghejian/dir/spdk/dpdk/build/lib/librte_rcu.a'),
        #     'numa',
        #     'isal',
        #     'rt',
        #     'uuid',
        #     'crypto',
        #     'aio',
        #     ],
        LIBDEPS_PRIVATE= [
            'oplog_stone_parameters',
            '$BUILD_DIR/mongo/db/db_raii',
            '$BUILD_DIR/mongo/db/catalog/database_holder',
            '$BUILD_DIR/mongo/db/commands/server_status',
            '$BUILD_DIR/mongo/db/snapshot_window_options',
            '$BUILD_DIR/mongo/db/storage/downgraded_unique_indexes',
            '$BUILD_DIR/mongo/db/storage/storage_repair_observer',
            '$BUILD_DIR/mongo/util/options_parser/options_parser',
            ],
        )

    wtEnv.Library(
        target='storage_wiredtiger',
        source=[
            'wiredtiger_init.cpp',
            'wiredtiger_options_init.cpp',
            'wiredtiger_server_status.cpp',
            'wiredtiger_global_options.idl',
        ],
        LIBDEPS=[
            'storage_wiredtiger_core',
            'storage_wiredtiger_customization_hooks',
            '$BUILD_DIR/mongo/db/db_raii',
            '$BUILD_DIR/mongo/db/storage/storage_engine_impl',
            '$BUILD_DIR/mongo/db/storage/storage_engine_lock_file',
            '$BUILD_DIR/mongo/db/storage/storage_engine_metadata',
        ],
        LIBDEPS_PRIVATE=[
            '$BUILD_DIR/mongo/db/catalog/database_holder',
            '$BUILD_DIR/mongo/db/commands/server_status',
            '$BUILD_DIR/mongo/db/concurrency/lock_manager',
            '$BUILD_DIR/mongo/db/storage/storage_engine_common',
            '$BUILD_DIR/mongo/util/options_parser/options_parser',
        ],
    )

    wtEnv.CppUnitTest(
        target='storage_wiredtiger_test',
        source=[
            'wiredtiger_init_test.cpp',
            'wiredtiger_kv_engine_test.cpp',
            'wiredtiger_recovery_unit_test.cpp',
            'wiredtiger_session_cache_test.cpp',
            'wiredtiger_util_test.cpp',
        ],
        LIBDEPS=[
            'storage_wiredtiger_core',
            '$BUILD_DIR/mongo/db/auth/authmocks',
            '$BUILD_DIR/mongo/db/service_context',
            '$BUILD_DIR/mongo/db/service_context_d',
            '$BUILD_DIR/mongo/db/service_context_test_fixture',
            '$BUILD_DIR/mongo/db/storage/durable_catalog_impl',
            '$BUILD_DIR/mongo/db/storage/kv/kv_engine_test_harness',
            '$BUILD_DIR/mongo/db/storage/recovery_unit_test_harness',
            '$BUILD_DIR/mongo/db/storage/storage_engine_metadata',
            '$BUILD_DIR/mongo/db/storage/storage_options',
            '$BUILD_DIR/mongo/db/storage/wiredtiger/storage_wiredtiger',
            '$BUILD_DIR/mongo/db/storage/wiredtiger/storage_wiredtiger_core',
            '$BUILD_DIR/mongo/util/clock_source_mock',
        ],
        LIBDEPS_PRIVATE=[
            '$BUILD_DIR/mongo/db/auth/authmocks',
            '$BUILD_DIR/mongo/db/index/index_access_methods',
            '$BUILD_DIR/mongo/db/repl/replmocks',
            '$BUILD_DIR/mongo/db/repl/repl_coordinator_interface',
            '$BUILD_DIR/mongo/db/service_context_test_fixture',
        ]
    )

    wtEnv.Library(
        target='additional_wiredtiger_record_store_tests',
        source=[
            'wiredtiger_record_store_test.cpp',
        ],
        LIBDEPS=[
            '$BUILD_DIR/mongo/db/storage/durable_catalog_impl',
            '$BUILD_DIR/mongo/db/storage/record_store_test_harness',
            '$BUILD_DIR/mongo/util/clock_source_mock',
            'storage_wiredtiger_core',
        ],
    )

    wtEnv.Library(
        target='additional_wiredtiger_index_tests',
        source=[
            'wiredtiger_index_test.cpp',
        ],
        LIBDEPS=[
            '$BUILD_DIR/mongo/db/storage/durable_catalog_impl',
            '$BUILD_DIR/mongo/db/storage/sorted_data_interface_test_harness',
            'storage_wiredtiger_core',
        ],
    )

    wtEnv.Library(
        target='oplog_stone_parameters',
        source=[
            'oplog_stone_parameters.idl',
        ],
        LIBDEPS=[
            '$BUILD_DIR/mongo/idl/server_parameter',
        ],
    )

    # All of these tests fail to compile under undefined behavior
    # sanitizer due to unexpressed circular dependency edges. In particular
    # they all need a definition from the 'catalog'.
    if not using_ubsan:
        wtEnv.CppUnitTest(
            target='storage_wiredtiger_record_store_and_index_test',
            source=[
                'wiredtiger_standard_index_test.cpp',
                'wiredtiger_standard_record_store_test.cpp',
            ],
            LIBDEPS=[
                'additional_wiredtiger_index_tests',
                'additional_wiredtiger_record_store_tests',
            ],
            LIBDEPS_PRIVATE=[
                '$BUILD_DIR/mongo/db/auth/authmocks',
                '$BUILD_DIR/mongo/db/repl/replmocks',
                '$BUILD_DIR/mongo/db/repl/repl_coordinator_interface',
                '$BUILD_DIR/mongo/db/service_context_test_fixture',
            ],
        )

        wtEnv.CppUnitTest(
            target='storage_wiredtiger_prefixed_record_store_and_index_test',
            source=[
                'wiredtiger_prefixed_index_test.cpp',
                'wiredtiger_prefixed_record_store_test.cpp',
            ],
            LIBDEPS=[
                'additional_wiredtiger_index_tests',
                'additional_wiredtiger_record_store_tests',
            ],
            LIBDEPS_PRIVATE=[
                '$BUILD_DIR/mongo/db/auth/authmocks',
                '$BUILD_DIR/mongo/db/repl/replmocks',
                '$BUILD_DIR/mongo/db/repl/repl_coordinator_interface',
                '$BUILD_DIR/mongo/db/service_context_test_fixture',
            ],
        )

        wtEnv.Benchmark(
            target='storage_wiredtiger_begin_transaction_block_bm',
            source='wiredtiger_begin_transaction_block_bm.cpp',
            LIBDEPS=[
                '$BUILD_DIR/mongo/db/service_context',
                '$BUILD_DIR/mongo/db/storage/durable_catalog_impl',
                '$BUILD_DIR/mongo/unittest/unittest',
                '$BUILD_DIR/mongo/util/clock_source_mock',
                'storage_wiredtiger_core',
            ],
       )
